---
title: "General Social Survey"
date: '2017-10-31T22:26:13-05:00'
description: ''
draft: no
image: pic04.jpg
keywords: ''
slug: blog3
categories:
- ''
- ''
---



<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>#calculate proportion of Yes&#39;s for snap_insta
proportion_snap_insta &lt;- gss %&gt;%
  filter(snapchat %in% c(&quot;Yes&quot;,&quot;No&quot;,&quot;NA&quot;),
         instagrm %in% c(&quot;Yes&quot;,&quot;No&quot;,&quot;NA&quot;)) %&gt;%
  mutate(snap_insta=case_when(
    snapchat==&quot;Yes&quot; | instagrm==&quot;Yes&quot; ~ &quot;Yes&quot;,
    snapchat==&quot;NA&quot; &amp; instagrm==&quot;NA&quot; ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;)) %&gt;% filter(snap_insta!=&quot;NA&quot;) %&gt;% 
  specify(response=snap_insta,success=&quot;Yes&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)

#calculate snap_insta ci
snap_insta_ci &lt;- proportion_snap_insta %&gt;% 
   get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)

#visualize snap_insta ci
proportion_snap_insta %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = snap_insta_ci)</code></pre>
<p><img src="/blogs/blog3_files/figure-html/read_gss_data2-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>snap_insta_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.351    0.401</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
<li>Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
<li>Do these two Confidence Intervals overlap?</li>
</ol>
</div>
<div id="proportion-of-bachelor-graduate" class="section level2">
<h2>Proportion of bachelor graduate:</h2>
<pre class="r"><code># Split degree into factor variables
twitter_gss &lt;- gss %&gt;% 
  mutate(degree=factor(degree,
                       levels = c(
                         &quot;Lt high school&quot;,
                         &quot;High School&quot;,
                         &quot;Junior college&quot;,
                         &quot;Bachelor&quot;,
                         &quot;Graduate&quot;),
                       ordered=TRUE))

# create bachelor_degree var
twitter_gss &lt;- gss %&gt;% 
  mutate(bachelor_degree=case_when(
    degree==&quot;Bachelor&quot; |degree==&quot;Graduate&quot; ~ &quot;Yes&quot;,
    is.na(degree) ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;
  ))

#create sample proportion
twitter_prop &lt;- twitter_gss %&gt;%
  filter(bachelor_degree==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;% 
  summarise(twitter_yes=mean(twitter==&quot;Yes&quot;),
            twitter_no=mean(twitter==&quot;No&quot;))
twitter_prop</code></pre>
<pre><code>## # A tibble: 1 x 2
##   twitter_yes twitter_no
##         &lt;dbl&gt;      &lt;dbl&gt;
## 1       0.233      0.767</code></pre>
</div>
<div id="confidence-interval-for-bachelor-graduate-who-use-twitter" class="section level2">
<h2>95% Confidence interval for bachelor graduate who use Twitter:</h2>
<pre class="r"><code># create bachelor_degree var
twitter_gss &lt;- gss %&gt;% 
  mutate(bachelor_degree=case_when(
    degree==&quot;Bachelor&quot; |degree==&quot;Graduate&quot; ~ &quot;Yes&quot;,
    is.na(degree) ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;
  ))

twitter_user_yes &lt;- twitter_gss %&gt;% 
  filter(bachelor_degree==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;%
  specify(response=twitter,success=&quot;Yes&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)

#create confidence interval
twitter_user_yes_ci &lt;- twitter_user_yes %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)

#visualize twitter_user_yes ci
twitter_user_yes %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = twitter_user_yes_ci)</code></pre>
<p><img src="/blogs/blog3_files/figure-html/twitter_yes-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>twitter_user_yes_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.196    0.270</code></pre>
<div id="confidence-interval-for-bachelor-graduate-who-do-not-use-twitter" class="section level3">
<h3>95% Confidence interval for bachelor graduate who do not use Twitter</h3>
<pre class="r"><code># create bachelor_degree var
twitter_gss &lt;- gss %&gt;% 
  mutate(bachelor_degree=case_when(
    degree==&quot;Bachelor&quot; |degree==&quot;Graduate&quot; ~ &quot;Yes&quot;,
    is.na(degree) ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;
  ))

twitter_user_no &lt;- twitter_gss %&gt;% 
  filter(bachelor_degree==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;%
  specify(response=twitter,success=&quot;No&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)

#create confidence interval
twitter_user_no_ci &lt;- twitter_user_no %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)

#visualize twitter_user_no ci
twitter_user_no %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = twitter_user_no_ci)</code></pre>
<p><img src="/blogs/blog3_files/figure-html/twitter_no-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>twitter_user_no_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.726    0.806</code></pre>
<p>According to the graphs above, among individuals who have a ‘bachelor’ degree or higher, the proportion that use Twitter overlaps with the confidence interval for people who do not use Twitter. This occurs at the higher end of the two confidence intervals because people who do not use Twitter fall into the interval 73%-81%, and people who do use Twitter fall into the interval 19%-27%.</p>
</div>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
<li>Visualise the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly. Is the mean or the median a better measure of the typical amoung of time Americans spend on email weekly? Why?</li>
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes). If you get a result that seems a bit odd, discuss why you think this might be the case.</li>
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<pre class="r"><code>email &lt;- gss %&gt;% 
  mutate(emailhr=as.numeric(emailhr),emailmin=as.numeric(emailmin))

email &lt;- email %&gt;%
  mutate(emailmin_total=emailhr*60+emailmin)
skim(email %&gt;% select(emailmin_total))</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
(#tab:email_usage_skim)Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
email %&gt;% select(emailmin…
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
2867
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
emailmin_total
</td>
<td style="text-align:right;">
1218
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
417
</td>
<td style="text-align:right;">
680
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
480
</td>
<td style="text-align:right;">
6000
</td>
<td style="text-align:left;">
&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
</tbody>
</table>
<p>The mean is 417 while the median is 120. Because of the data set and the number of outliers, we can assume that the median is the more accurate measure.</p>
<pre class="r"><code>email &lt;- email %&gt;% 
  specify(response=emailmin_total) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;mean&quot;)

email_ci &lt;- email %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;) %&gt;% 
  mutate(lower_ci_hrs=lower_ci%/%60,lower_ci_mins=lower_ci%%60,
         upper_ci_hrs=upper_ci%/%60,upper_ci_mins=upper_ci%%60) 

# visualize email_ci
email_ci</code></pre>
<pre><code>## # A tibble: 1 x 6
##   lower_ci upper_ci lower_ci_hrs lower_ci_mins upper_ci_hrs upper_ci_mins
##      &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;
## 1     385.     450.            6          25.2            7          29.9</code></pre>
<p>The lower confidence interval is 386.77 minutes (6 hours, 26.77 minutes), and the upper confidence interval is 446.87 minutes (7 hours,26.87 minutes). If we increase the confidence interval to 99%, we would project the range to be larger to make sure that the result would be in the range. As a result, the lower confidence interval would be smaller than 386 minutes and the higher confidence interval would be bigger than 446 minutes.</p>
</div>
